#pragma once

#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define MIN(a, b) ((a) < (b) ? (a) : (b))

#define NOZZLE_PROBE_OFFSET_X 50
#define NOZZLE_PROBE_OFFSET_Y 0
#define NOZZLE_PROBE_OFFSET_Z -3

#define MAX_PROBE_ERROR_DIFF 3

#define ZONESTAR_P802QS_MESH_MIN_X MAX(MESH_INSET, X_MIN_POS + NOZZLE_PROBE_OFFSET_X)
#define ZONESTAR_P802QS_MESH_MIN_Y MAX(MESH_INSET, Y_MIN_POS + NOZZLE_PROBE_OFFSET_Y)

#define ZONESTAR_P802QS_PROBE_INSET 10